### ISSUE TITLE
INRUPT solid api does not support Node 18 + React dedupes?

### ISSUE THREAD

**Issue by FdezAriasSara** [Arquisoft/lomap_en3b#28]
While trying to enhance the aesthetics and accessibility of the Login , I had to do npm dedupe some packages since some elements had the same dependencies and lead to package duplications. 

While managing the packages and trying to clean everything up a little, using :
              -npm dedupe
              -npm prune

**I obtained the following WARNING messages (both times)  :** 

![image](https://user-images.githubusercontent.com/79209608/224480957-b5ebfc78-4251-4122-840a-d2c7fcb6d291.png)

After some research, i found the following Issue addressing this matter: 

![image](https://user-images.githubusercontent.com/79209608/224480949-c0d78720-13d3-48ec-b5cd-89305ab0a3cb.png)

[issue in Inrupt/solid-client ](https://github.com/inrupt/solid-client-js/issues/1775)

moreover , one of Inrupt solid contributors answered that **"_(..) we don't support Node 18 at the moment. We are working on getting this support in, but it is a non-trivial task for our authentication library, because of changes to fetch in Node 18(..).":_**

[devs comment ](https://github.com/inrupt/solid-client-js/issues/1775#issuecomment-1327476133)

**It does work , but I think it will be problematic with other elements of the app  sooner or later... **  

So... i guess the only chance we have to remove this warning is to downgrade the node version to one that is actually compatible with inrupt?  ( _i think , after looking at npm's error message that the greatest allowed is 16.0.0)_ ?

@pglez82

**Comment by pglez82** [comment]
Ok. That is very unfortunate, but the issue seems very clear: they do not support node 18.

The only thing that is not that clear to me is that in my example project:

https://github.com/pglez82/solid-react-example

it works with node 18 (I can login to solid and retrieve information from the pod). The only thing is that I am installing the dependencies with ```npm install --legacy-peer-deps```. 

So, in the short run, I would try this option, to see if it is a quick fix for your issue. In the long run, I would downgrade the project to node 16. Actually is not that difficult. You can take as an example last year's template that used node 16:

https://github.com/pglez82/asw2122_0/tree/master/webapp

I hope this helps,

Pablo
